name: Configuring TomCat with Maven

on:
    push:
        branches: ["main"]

jobs:
    Build-Maven:

        runs-on: ubuntu-latest

        steps:
            - name: Clone Repository
              uses: actions/checkout@v3

            - name: Install JDK 11
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distrbution: 'temurin'
                cache: maven

            - name: Build package with Maven
              run: mvn clean package

            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                name: xashy-app
                path: target/*.war